// Mocks generated by Mockito 5.2.0 from annotations
// in auth_service/test/method/method.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:auth_service/src/method/apple.dart' as _i9;
import 'package:auth_service/src/method/facebook.dart' as _i8;
import 'package:auth_service/src/method/google.dart' as _i5;
import 'package:auth_service/src/method/twitter.dart' as _i10;
import 'package:flutter_facebook_auth/flutter_facebook_auth.dart' as _i2;
import 'package:google_sign_in/google_sign_in.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sign_in_with_apple/sign_in_with_apple.dart' as _i3;
import 'package:twitter_login/entity/auth_result.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeLoginResult_0 extends _i1.Fake implements _i2.LoginResult {}

class _FakeAuthorizationCredentialAppleID_1 extends _i1.Fake
    implements _i3.AuthorizationCredentialAppleID {}

class _FakeAuthResult_2 extends _i1.Fake implements _i4.AuthResult {}

/// A class which mocks [GoogleAuthClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleAuthClient extends _i1.Mock implements _i5.GoogleAuthClient {
  MockGoogleAuthClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i7.GoogleSignInAccount?> signIn() =>
      (super.noSuchMethod(Invocation.method(#signIn, []),
              returnValue: Future<_i7.GoogleSignInAccount?>.value())
          as _i6.Future<_i7.GoogleSignInAccount?>);
}

/// A class which mocks [FacebookAuthClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockFacebookAuthClient extends _i1.Mock
    implements _i8.FacebookAuthClient {
  MockFacebookAuthClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.LoginResult> login(
          {List<String>? permissions = const [r'email', r'public_profile'],
          _i2.LoginBehavior? loginBehavior = _i2.LoginBehavior.dialogOnly}) =>
      (super.noSuchMethod(
              Invocation.method(#login, [],
                  {#permissions: permissions, #loginBehavior: loginBehavior}),
              returnValue: Future<_i2.LoginResult>.value(_FakeLoginResult_0()))
          as _i6.Future<_i2.LoginResult>);
}

/// A class which mocks [AppleAuthClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppleAuthClient extends _i1.Mock implements _i9.AppleAuthClient {
  MockAppleAuthClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.AuthorizationCredentialAppleID> getAppleIDCredential(
          {String? rawNonce}) =>
      (super.noSuchMethod(
          Invocation.method(#getAppleIDCredential, [], {#rawNonce: rawNonce}),
          returnValue: Future<_i3.AuthorizationCredentialAppleID>.value(
              _FakeAuthorizationCredentialAppleID_1())) as _i6
          .Future<_i3.AuthorizationCredentialAppleID>);
}

/// A class which mocks [TwitterAuthClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTwitterAuthClient extends _i1.Mock implements _i10.TwitterAuthClient {
  MockTwitterAuthClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.AuthResult> login(
          {String? apiKey,
          String? apiSecretKey,
          String? redirectURI,
          bool? forceLogin = false}) =>
      (super.noSuchMethod(
              Invocation.method(#login, [], {
                #apiKey: apiKey,
                #apiSecretKey: apiSecretKey,
                #redirectURI: redirectURI,
                #forceLogin: forceLogin
              }),
              returnValue: Future<_i4.AuthResult>.value(_FakeAuthResult_2()))
          as _i6.Future<_i4.AuthResult>);
}
