include: all_lint_rules.yaml
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    included_file_warning: ignore
  exclude:
    - packages/**/*.freezed.dart
    - packages/**/*.g.dart
    - packages/**/*.mocks.dart
linter:
  rules:
    always_use_package_imports: false
    avoid_final_parameters: false
    avoid_types_on_closure_parameters: false
    lines_longer_than_80_chars: false
    no_leading_underscores_for_library_prefixes: false
    no_leading_underscores_for_local_identifiers: false
    omit_local_variable_types: false
    one_member_abstracts: false
    prefer_double_quotes: false
    prefer_single_quotes: false
    secure_pubspec_urls: false
    unnecessary_constructor_name: false
    unnecessary_final: false
