name: modules_workspace
description: A Dart / Flutter modules project.
homepage: https://github.com/nagakuta

environment:
  sdk: ^3.0.0

dev_dependencies:
  fvm: ^3.0.0
  mason_cli: ^0.1.0-dev.0
  melos: ^4.0.0
