// ignore_for_file: constant_identifier_names, public_member_api_docs

const double DESKTOP_LANDSCAPE_LAYOUT_MIN_WIDTH = 1280;
const double LARGE_TABLET_LANDSCAPE_LAYOUT_MIN_WIDTH = 1024;
const double SMALL_TABLET_LANDSCAPE_LAYOUT_MIN_WIDTH = 960;
const double LARGE_HANDSET_LANDSCAPE_LAYOUT_MIN_WIDTH = 720;
const double MEDIUM_HANDSET_LANDSCAPE_LAYOUT_MIN_WIDTH = 600;
const double SMALL_HANDSET_LANDSCAPE_LAYOUT_MIN_WIDTH = 0;

const double DESKTOP_PORTRAIT_LAYOUT_MIN_WIDTH = 840;
const double LARGE_TABLET_PORTRAIT_LAYOUT_MIN_WIDTH = 720;
const double SMALL_TABLET_PORTRAIT_LAYOUT_MIN_WIDTH = 600;
const double LARGE_HANDSET_PORTRAIT_LAYOUT_MIN_WIDTH = 400;
const double MEDIUM_HANDSET_PORTRAIT_LAYOUT_MIN_WIDTH = 360;
const double SMALL_HANDSET_PORTRAIT_LAYOUT_MIN_WIDTH = 0;

const double EXTRA_LARGE_WINDOW_MIN_WIDTH = 1600;
const double LARGE_WINDOW_MIN_WIDTH = 1440;
const double EXPANDED_WINDOW_MIN_WIDTH = 1024;
const double MEDIUM_WINDOW_MIN_WIDTH = 600;
const double COMPACT_WINDOW_MIN_WIDTH = 0;
