name: Setup Flutter Application
runs:
  using: composite
  steps:
    - name: Set PATH
      shell: bash
      run: echo "/github/home/.pub-cache/bin" >> $GITHUB_PATH
    - name: Activate FVM
      shell: bash
      run: dart pub global activate fvm \<4.0.0
    - name: Setup Flutter
      shell: bash
      run: fvm install --setup
