// Mocks generated by Mockito 5.3.0 from annotations
// in analytics_service/src/service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:analytics_service/src/service.dart' as _i3;
import 'package:firebase_analytics/firebase_analytics.dart' as _i2;
import 'package:flutter/services.dart' as _i4;
import 'package:flutter/widgets.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseAnalyticsObserver_0 extends _i1.SmartFake
    implements _i2.FirebaseAnalyticsObserver {
  _FakeFirebaseAnalyticsObserver_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeFirebaseAnalytics_1 extends _i1.SmartFake
    implements _i2.FirebaseAnalytics {
  _FakeFirebaseAnalytics_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i3.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseAnalyticsObserver observe(
          {_i2.ScreenNameExtractor? nameExtractor = _i2.defaultNameExtractor,
          _i2.RouteFilter? routeFilter = _i2.defaultRouteFilter,
          dynamic Function(_i4.PlatformException)? onError}) =>
      (super.noSuchMethod(
          Invocation.method(#observe, [], {
            #nameExtractor: nameExtractor,
            #routeFilter: routeFilter,
            #onError: onError
          }),
          returnValue: _FakeFirebaseAnalyticsObserver_0(
              this,
              Invocation.method(#observe, [], {
                #nameExtractor: nameExtractor,
                #routeFilter: routeFilter,
                #onError: onError
              }))) as _i2.FirebaseAnalyticsObserver);
  @override
  void logEvent({String? name, Map<String, Object?>? parameters}) =>
      super.noSuchMethod(
          Invocation.method(
              #logEvent, [], {#name: name, #parameters: parameters}),
          returnValueForMissingStub: null);
  @override
  void setConsent(
          {bool? adStorageConsentGranted,
          bool? analyticsStorageConsentGranted}) =>
      super.noSuchMethod(
          Invocation.method(#setConsent, [], {
            #adStorageConsentGranted: adStorageConsentGranted,
            #analyticsStorageConsentGranted: analyticsStorageConsentGranted
          }),
          returnValueForMissingStub: null);
  @override
  void logScreenView({String? screenName, String? screenClass = r'Flutter'}) =>
      super.noSuchMethod(
          Invocation.method(#logScreenView, [],
              {#screenName: screenName, #screenClass: screenClass}),
          returnValueForMissingStub: null);
  @override
  void setUserProperty({String? name, String? value}) => super.noSuchMethod(
      Invocation.method(#setUserProperty, [], {#name: name, #value: value}),
      returnValueForMissingStub: null);
  @override
  void logAddPaymentInfo(
          {String? coupon,
          String? currency,
          String? paymentType,
          double? value,
          List<_i2.AnalyticsEventItem>? items}) =>
      super.noSuchMethod(
          Invocation.method(#logAddPaymentInfo, [], {
            #coupon: coupon,
            #currency: currency,
            #paymentType: paymentType,
            #value: value,
            #items: items
          }),
          returnValueForMissingStub: null);
  @override
  void logAddShippingInfo(
          {String? coupon,
          String? currency,
          double? value,
          String? shippingTier,
          List<_i2.AnalyticsEventItem>? items}) =>
      super.noSuchMethod(
          Invocation.method(#logAddShippingInfo, [], {
            #coupon: coupon,
            #currency: currency,
            #value: value,
            #shippingTier: shippingTier,
            #items: items
          }),
          returnValueForMissingStub: null);
  @override
  void logAddToCart(
          {List<_i2.AnalyticsEventItem>? items,
          double? value,
          String? currency}) =>
      super.noSuchMethod(
          Invocation.method(#logAddToCart, [],
              {#items: items, #value: value, #currency: currency}),
          returnValueForMissingStub: null);
  @override
  void logAddToWishlist(
          {List<_i2.AnalyticsEventItem>? items,
          double? value,
          String? currency}) =>
      super.noSuchMethod(
          Invocation.method(#logAddToWishlist, [],
              {#items: items, #value: value, #currency: currency}),
          returnValueForMissingStub: null);
  @override
  void logAdImpression(
          {String? adPlatform,
          String? adSource,
          String? adFormat,
          String? adUnitName,
          double? value,
          String? currency}) =>
      super.noSuchMethod(
          Invocation.method(#logAdImpression, [], {
            #adPlatform: adPlatform,
            #adSource: adSource,
            #adFormat: adFormat,
            #adUnitName: adUnitName,
            #value: value,
            #currency: currency
          }),
          returnValueForMissingStub: null);
  @override
  void logAppOpen() => super.noSuchMethod(Invocation.method(#logAppOpen, []),
      returnValueForMissingStub: null);
  @override
  void logBeginCheckout(
          {double? value,
          String? currency,
          List<_i2.AnalyticsEventItem>? items,
          String? coupon}) =>
      super.noSuchMethod(
          Invocation.method(#logBeginCheckout, [], {
            #value: value,
            #currency: currency,
            #items: items,
            #coupon: coupon
          }),
          returnValueForMissingStub: null);
  @override
  void logCampaignDetails(
          {String? source,
          String? medium,
          String? campaign,
          String? term,
          String? content,
          String? aclid,
          String? cp1}) =>
      super.noSuchMethod(
          Invocation.method(#logCampaignDetails, [], {
            #source: source,
            #medium: medium,
            #campaign: campaign,
            #term: term,
            #content: content,
            #aclid: aclid,
            #cp1: cp1
          }),
          returnValueForMissingStub: null);
  @override
  void logEarnVirtualCurrency({String? virtualCurrencyName, num? value}) =>
      super.noSuchMethod(
          Invocation.method(#logEarnVirtualCurrency, [],
              {#virtualCurrencyName: virtualCurrencyName, #value: value}),
          returnValueForMissingStub: null);
  @override
  void logGenerateLead({String? currency, double? value}) => super.noSuchMethod(
      Invocation.method(
          #logGenerateLead, [], {#currency: currency, #value: value}),
      returnValueForMissingStub: null);
  @override
  void logJoinGroup({String? groupId}) => super.noSuchMethod(
      Invocation.method(#logJoinGroup, [], {#groupId: groupId}),
      returnValueForMissingStub: null);
  @override
  void logLevelUp({int? level, String? character}) => super.noSuchMethod(
      Invocation.method(
          #logLevelUp, [], {#level: level, #character: character}),
      returnValueForMissingStub: null);
  @override
  void logLevelStart({String? levelName}) => super.noSuchMethod(
      Invocation.method(#logLevelStart, [], {#levelName: levelName}),
      returnValueForMissingStub: null);
  @override
  void logLevelEnd({String? levelName, int? success}) => super.noSuchMethod(
      Invocation.method(
          #logLevelEnd, [], {#levelName: levelName, #success: success}),
      returnValueForMissingStub: null);
  @override
  void logSetCheckoutOption({int? checkoutStep, String? checkoutOption}) =>
      super.noSuchMethod(
          Invocation.method(#logSetCheckoutOption, [],
              {#checkoutStep: checkoutStep, #checkoutOption: checkoutOption}),
          returnValueForMissingStub: null);
  @override
  void logLogin({String? userId, String? loginMethod}) => super.noSuchMethod(
      Invocation.method(
          #logLogin, [], {#userId: userId, #loginMethod: loginMethod}),
      returnValueForMissingStub: null);
  @override
  void logPostScore({int? score, int? level, String? character}) =>
      super.noSuchMethod(
          Invocation.method(#logPostScore, [],
              {#score: score, #level: level, #character: character}),
          returnValueForMissingStub: null);
  @override
  void logPurchase(
          {String? currency,
          String? coupon,
          double? value,
          List<_i2.AnalyticsEventItem>? items,
          double? tax,
          double? shipping,
          String? transactionId,
          String? affiliation}) =>
      super.noSuchMethod(
          Invocation.method(#logPurchase, [], {
            #currency: currency,
            #coupon: coupon,
            #value: value,
            #items: items,
            #tax: tax,
            #shipping: shipping,
            #transactionId: transactionId,
            #affiliation: affiliation
          }),
          returnValueForMissingStub: null);
  @override
  void logRemoveFromCart(
          {String? currency,
          double? value,
          List<_i2.AnalyticsEventItem>? items}) =>
      super.noSuchMethod(
          Invocation.method(#logRemoveFromCart, [],
              {#currency: currency, #value: value, #items: items}),
          returnValueForMissingStub: null);
  @override
  void logSelectItem(
          {String? itemListId,
          String? itemListName,
          List<_i2.AnalyticsEventItem>? items}) =>
      super.noSuchMethod(
          Invocation.method(#logSelectItem, [], {
            #itemListId: itemListId,
            #itemListName: itemListName,
            #items: items
          }),
          returnValueForMissingStub: null);
  @override
  void logSelectPromotion(
          {String? creativeName,
          String? creativeSlot,
          List<_i2.AnalyticsEventItem>? items,
          String? locationId,
          String? promotionId,
          String? promotionName}) =>
      super.noSuchMethod(
          Invocation.method(#logSelectPromotion, [], {
            #creativeName: creativeName,
            #creativeSlot: creativeSlot,
            #items: items,
            #locationId: locationId,
            #promotionId: promotionId,
            #promotionName: promotionName
          }),
          returnValueForMissingStub: null);
  @override
  void logViewCart(
          {String? currency,
          double? value,
          List<_i2.AnalyticsEventItem>? items}) =>
      super.noSuchMethod(
          Invocation.method(#logViewCart, [],
              {#currency: currency, #value: value, #items: items}),
          returnValueForMissingStub: null);
  @override
  void logSearch(
          {String? searchTerm,
          int? numberOfNights,
          int? numberOfRooms,
          int? numberOfPassengers,
          String? origin,
          String? destination,
          DateTime? startDate,
          DateTime? endDate,
          String? travelClass}) =>
      super.noSuchMethod(
          Invocation.method(#logSearch, [], {
            #searchTerm: searchTerm,
            #numberOfNights: numberOfNights,
            #numberOfRooms: numberOfRooms,
            #numberOfPassengers: numberOfPassengers,
            #origin: origin,
            #destination: destination,
            #startDate: startDate,
            #endDate: endDate,
            #travelClass: travelClass
          }),
          returnValueForMissingStub: null);
  @override
  void logSelectContent({String? contentType, String? itemId}) =>
      super.noSuchMethod(
          Invocation.method(#logSelectContent, [],
              {#contentType: contentType, #itemId: itemId}),
          returnValueForMissingStub: null);
  @override
  void logShare({String? contentType, String? itemId, String? method}) =>
      super.noSuchMethod(
          Invocation.method(#logShare, [],
              {#contentType: contentType, #itemId: itemId, #method: method}),
          returnValueForMissingStub: null);
  @override
  void logSignUp({String? userId, String? signUpMethod}) => super.noSuchMethod(
      Invocation.method(
          #logSignUp, [], {#userId: userId, #signUpMethod: signUpMethod}),
      returnValueForMissingStub: null);
  @override
  void logSpendVirtualCurrency(
          {String? itemName, String? virtualCurrencyName, num? value}) =>
      super.noSuchMethod(
          Invocation.method(#logSpendVirtualCurrency, [], {
            #itemName: itemName,
            #virtualCurrencyName: virtualCurrencyName,
            #value: value
          }),
          returnValueForMissingStub: null);
  @override
  void logTutorialBegin() =>
      super.noSuchMethod(Invocation.method(#logTutorialBegin, []),
          returnValueForMissingStub: null);
  @override
  void logTutorialComplete() =>
      super.noSuchMethod(Invocation.method(#logTutorialComplete, []),
          returnValueForMissingStub: null);
  @override
  void logUnlockAchievement({String? id}) => super.noSuchMethod(
      Invocation.method(#logUnlockAchievement, [], {#id: id}),
      returnValueForMissingStub: null);
  @override
  void logViewItem(
          {String? currency,
          double? value,
          List<_i2.AnalyticsEventItem>? items}) =>
      super.noSuchMethod(
          Invocation.method(#logViewItem, [],
              {#currency: currency, #value: value, #items: items}),
          returnValueForMissingStub: null);
  @override
  void logViewItemList(
          {List<_i2.AnalyticsEventItem>? items,
          String? itemListId,
          String? itemListName}) =>
      super.noSuchMethod(
          Invocation.method(#logViewItemList, [], {
            #items: items,
            #itemListId: itemListId,
            #itemListName: itemListName
          }),
          returnValueForMissingStub: null);
  @override
  void logViewPromotion(
          {String? creativeName,
          String? creativeSlot,
          List<_i2.AnalyticsEventItem>? items,
          String? locationId,
          String? promotionId,
          String? promotionName}) =>
      super.noSuchMethod(
          Invocation.method(#logViewPromotion, [], {
            #creativeName: creativeName,
            #creativeSlot: creativeSlot,
            #items: items,
            #locationId: locationId,
            #promotionId: promotionId,
            #promotionName: promotionName
          }),
          returnValueForMissingStub: null);
  @override
  void logViewSearchResults({String? searchTerm}) => super.noSuchMethod(
      Invocation.method(#logViewSearchResults, [], {#searchTerm: searchTerm}),
      returnValueForMissingStub: null);
  @override
  void logRefund(
          {String? currency,
          String? coupon,
          double? value,
          double? tax,
          double? shipping,
          String? transactionId,
          String? affiliation,
          List<_i2.AnalyticsEventItem>? items}) =>
      super.noSuchMethod(
          Invocation.method(#logRefund, [], {
            #currency: currency,
            #coupon: coupon,
            #value: value,
            #tax: tax,
            #shipping: shipping,
            #transactionId: transactionId,
            #affiliation: affiliation,
            #items: items
          }),
          returnValueForMissingStub: null);
  @override
  void logLogout({String? userId}) =>
      super.noSuchMethod(Invocation.method(#logLogout, [], {#userId: userId}),
          returnValueForMissingStub: null);
  @override
  void setDefaultEventParameters(Map<String, Object>? defaultParameters) =>
      super.noSuchMethod(
          Invocation.method(#setDefaultEventParameters, [defaultParameters]),
          returnValueForMissingStub: null);
  @override
  void setSessionTimeoutDuration(Duration? timeout) => super.noSuchMethod(
      Invocation.method(#setSessionTimeoutDuration, [timeout]),
      returnValueForMissingStub: null);
}

/// A class which mocks [FirebaseAnalyticsObserver].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAnalyticsObserver extends _i1.Mock
    implements _i2.FirebaseAnalyticsObserver {
  MockFirebaseAnalyticsObserver() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseAnalytics get analytics =>
      (super.noSuchMethod(Invocation.getter(#analytics),
              returnValue:
                  _FakeFirebaseAnalytics_1(this, Invocation.getter(#analytics)))
          as _i2.FirebaseAnalytics);
  @override
  _i2.ScreenNameExtractor get nameExtractor =>
      (super.noSuchMethod(Invocation.getter(#nameExtractor),
              returnValue: (_i5.RouteSettings settings) => null)
          as _i2.ScreenNameExtractor);
  @override
  _i2.RouteFilter get routeFilter => (super.noSuchMethod(
      Invocation.getter(#routeFilter),
      returnValue: (_i5.Route<dynamic>? route) => false) as _i2.RouteFilter);
  @override
  void didPush(_i5.Route<dynamic>? route, _i5.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didPush, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didReplace(
          {_i5.Route<dynamic>? newRoute, _i5.Route<dynamic>? oldRoute}) =>
      super.noSuchMethod(
          Invocation.method(
              #didReplace, [], {#newRoute: newRoute, #oldRoute: oldRoute}),
          returnValueForMissingStub: null);
  @override
  void didPop(_i5.Route<dynamic>? route, _i5.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didPop, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  bool debugObservingRoute(_i5.ModalRoute<dynamic>? route) =>
      (super.noSuchMethod(Invocation.method(#debugObservingRoute, [route]),
          returnValue: false) as bool);
  @override
  void subscribe(_i5.RouteAware? routeAware, _i5.ModalRoute<dynamic>? route) =>
      super.noSuchMethod(Invocation.method(#subscribe, [routeAware, route]),
          returnValueForMissingStub: null);
  @override
  void unsubscribe(_i5.RouteAware? routeAware) =>
      super.noSuchMethod(Invocation.method(#unsubscribe, [routeAware]),
          returnValueForMissingStub: null);
  @override
  void didRemove(
          _i5.Route<dynamic>? route, _i5.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(Invocation.method(#didRemove, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didStartUserGesture(
          _i5.Route<dynamic>? route, _i5.Route<dynamic>? previousRoute) =>
      super.noSuchMethod(
          Invocation.method(#didStartUserGesture, [route, previousRoute]),
          returnValueForMissingStub: null);
  @override
  void didStopUserGesture() =>
      super.noSuchMethod(Invocation.method(#didStopUserGesture, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [AnalyticsEventItem].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsEventItem extends _i1.Mock
    implements _i2.AnalyticsEventItem {
  MockAnalyticsEventItem() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> asMap() =>
      (super.noSuchMethod(Invocation.method(#asMap, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}
