version: '3.8'
services:
  flutter_modules:
    build:
      context: ../
      dockerfile: .devcontainer/flutter_modules/Dockerfile
    volumes:
      # VSCode
      - ../.vscode:/workspace/.vscode:cached
      # Git
      - ../.git:/workspace/.git:cached
      - ../.gitattributes:/workspace/.gitattributes:cached
      - ../.gitignore:/workspace/.gitignore:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file:
      - flutter_modules/.flutter.env
