// Mocks generated by Mockito 5.3.0 from annotations
// in logging_service/test/client.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:logging/logging.dart' as _i4;
import 'package:logging_service/src/client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LoggingClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoggingClient extends _i1.Mock implements _i2.LoggingClient {
  MockLoggingClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.LogRecord> get onRecord =>
      (super.noSuchMethod(Invocation.getter(#onRecord),
              returnValue: _i3.Stream<_i4.LogRecord>.empty())
          as _i3.Stream<_i4.LogRecord>);
  @override
  void log(_i4.Level? logLevel, Object? message,
          [Object? error, StackTrace? stackTrace, _i3.Zone? zone]) =>
      super.noSuchMethod(
          Invocation.method(#log, [logLevel, message, error, stackTrace, zone]),
          returnValueForMissingStub: null);
  @override
  void shout(Object? message, [Object? error, StackTrace? stackTrace]) => super
      .noSuchMethod(Invocation.method(#shout, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void severe(Object? message, [Object? error, StackTrace? stackTrace]) => super
      .noSuchMethod(Invocation.method(#severe, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void warning(Object? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
          Invocation.method(#warning, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void info(Object? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#info, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void config(Object? message, [Object? error, StackTrace? stackTrace]) => super
      .noSuchMethod(Invocation.method(#config, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void fine(Object? message, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(Invocation.method(#fine, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void finer(Object? message, [Object? error, StackTrace? stackTrace]) => super
      .noSuchMethod(Invocation.method(#finer, [message, error, stackTrace]),
          returnValueForMissingStub: null);
  @override
  void finest(Object? message, [Object? error, StackTrace? stackTrace]) => super
      .noSuchMethod(Invocation.method(#finest, [message, error, stackTrace]),
          returnValueForMissingStub: null);
}
