// Mocks generated by Mockito 5.3.0 from annotations
// in permission_service/test/client.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:permission_handler/permission_handler.dart' as _i4;
import 'package:permission_service/src/client.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PermissionClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionClient extends _i1.Mock implements _i2.PermissionClient {
  MockPermissionClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.PermissionStatus> getCalendarStatus() => (super.noSuchMethod(
      Invocation.method(#getCalendarStatus, []),
      returnValue: _i3.Future<_i4.PermissionStatus>.value(
          _i4.PermissionStatus.denied)) as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getCameraStatus() => (super.noSuchMethod(
      Invocation.method(#getCameraStatus, []),
      returnValue: _i3.Future<_i4.PermissionStatus>.value(
          _i4.PermissionStatus.denied)) as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getContactsStatus() => (super.noSuchMethod(
      Invocation.method(#getContactsStatus, []),
      returnValue: _i3.Future<_i4.PermissionStatus>.value(
          _i4.PermissionStatus.denied)) as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getLocationStatus() => (super.noSuchMethod(
      Invocation.method(#getLocationStatus, []),
      returnValue: _i3.Future<_i4.PermissionStatus>.value(
          _i4.PermissionStatus.denied)) as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getLocationAlwaysStatus() =>
      (super.noSuchMethod(Invocation.method(#getLocationAlwaysStatus, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getLocationWhenInUseStatus() =>
      (super.noSuchMethod(Invocation.method(#getLocationWhenInUseStatus, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getMediaLibraryStatus() =>
      (super.noSuchMethod(Invocation.method(#getMediaLibraryStatus, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getMicrophoneStatus() => (super.noSuchMethod(
      Invocation.method(#getMicrophoneStatus, []),
      returnValue: _i3.Future<_i4.PermissionStatus>.value(
          _i4.PermissionStatus.denied)) as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getPhoneStatus() => (super.noSuchMethod(
      Invocation.method(#getPhoneStatus, []),
      returnValue: _i3.Future<_i4.PermissionStatus>.value(
          _i4.PermissionStatus.denied)) as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getPhotosStatus() => (super.noSuchMethod(
      Invocation.method(#getPhotosStatus, []),
      returnValue: _i3.Future<_i4.PermissionStatus>.value(
          _i4.PermissionStatus.denied)) as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getPhotosAddOnlyStatus() =>
      (super.noSuchMethod(Invocation.method(#getPhotosAddOnlyStatus, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getRemindersStatus() => (super.noSuchMethod(
      Invocation.method(#getRemindersStatus, []),
      returnValue: _i3.Future<_i4.PermissionStatus>.value(
          _i4.PermissionStatus.denied)) as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getSensorsStatus() => (super.noSuchMethod(
      Invocation.method(#getSensorsStatus, []),
      returnValue: _i3.Future<_i4.PermissionStatus>.value(
          _i4.PermissionStatus.denied)) as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getSmsStatus() => (super.noSuchMethod(
      Invocation.method(#getSmsStatus, []),
      returnValue: _i3.Future<_i4.PermissionStatus>.value(
          _i4.PermissionStatus.denied)) as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getSpeechStatus() => (super.noSuchMethod(
      Invocation.method(#getSpeechStatus, []),
      returnValue: _i3.Future<_i4.PermissionStatus>.value(
          _i4.PermissionStatus.denied)) as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getStorageStatus() => (super.noSuchMethod(
      Invocation.method(#getStorageStatus, []),
      returnValue: _i3.Future<_i4.PermissionStatus>.value(
          _i4.PermissionStatus.denied)) as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getIgnoreBatteryOptimizationsStatus() =>
      (super.noSuchMethod(
              Invocation.method(#getIgnoreBatteryOptimizationsStatus, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getNotificationStatus() =>
      (super.noSuchMethod(Invocation.method(#getNotificationStatus, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getAccessMediaLocationStatus() =>
      (super.noSuchMethod(Invocation.method(#getAccessMediaLocationStatus, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getActivityRecognitionStatus() =>
      (super.noSuchMethod(Invocation.method(#getActivityRecognitionStatus, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getUnknownStatus() => (super.noSuchMethod(
      Invocation.method(#getUnknownStatus, []),
      returnValue: _i3.Future<_i4.PermissionStatus>.value(
          _i4.PermissionStatus.denied)) as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getBluetoothStatus() => (super.noSuchMethod(
      Invocation.method(#getBluetoothStatus, []),
      returnValue: _i3.Future<_i4.PermissionStatus>.value(
          _i4.PermissionStatus.denied)) as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getManageExternalStorageStatus() => (super
          .noSuchMethod(Invocation.method(#getManageExternalStorageStatus, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
      as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getSystemAlertWindowStatus() =>
      (super.noSuchMethod(Invocation.method(#getSystemAlertWindowStatus, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getRequestInstallPackagesStatus() => (super
          .noSuchMethod(Invocation.method(#getRequestInstallPackagesStatus, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
      as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getAppTrackingTransparencyStatus() => (super
      .noSuchMethod(Invocation.method(#getAppTrackingTransparencyStatus, []),
          returnValue: _i3.Future<_i4.PermissionStatus>.value(
              _i4.PermissionStatus.denied)) as _i3
      .Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getCriticalAlertsStatus() =>
      (super.noSuchMethod(Invocation.method(#getCriticalAlertsStatus, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getAccessNotificationPolicyStatus() => (super
      .noSuchMethod(Invocation.method(#getAccessNotificationPolicyStatus, []),
          returnValue: _i3.Future<_i4.PermissionStatus>.value(
              _i4.PermissionStatus.denied)) as _i3
      .Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getBluetoothScanStatus() =>
      (super.noSuchMethod(Invocation.method(#getBluetoothScanStatus, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getBluetoothAdvertiseStatus() =>
      (super.noSuchMethod(Invocation.method(#getBluetoothAdvertiseStatus, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> getBluetoothConnectStatus() =>
      (super.noSuchMethod(Invocation.method(#getBluetoothConnectStatus, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.ServiceStatus> getLocationServiceStatus() =>
      (super.noSuchMethod(Invocation.method(#getLocationServiceStatus, []),
          returnValue: _i3.Future<_i4.ServiceStatus>.value(
              _i4.ServiceStatus.disabled)) as _i3.Future<_i4.ServiceStatus>);
  @override
  _i3.Future<_i4.ServiceStatus> getLocationAlwaysServiceStatus() => (super
      .noSuchMethod(Invocation.method(#getLocationAlwaysServiceStatus, []),
          returnValue: _i3.Future<_i4.ServiceStatus>.value(
              _i4.ServiceStatus.disabled)) as _i3.Future<_i4.ServiceStatus>);
  @override
  _i3.Future<_i4.ServiceStatus> getLocationWhenInUseServiceStatus() => (super
      .noSuchMethod(Invocation.method(#getLocationWhenInUseServiceStatus, []),
          returnValue: _i3.Future<_i4.ServiceStatus>.value(
              _i4.ServiceStatus.disabled)) as _i3.Future<_i4.ServiceStatus>);
  @override
  _i3.Future<_i4.ServiceStatus> getPhoneServiceStatus() => (super.noSuchMethod(
          Invocation.method(#getPhoneServiceStatus, []),
          returnValue:
              _i3.Future<_i4.ServiceStatus>.value(_i4.ServiceStatus.disabled))
      as _i3.Future<_i4.ServiceStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestCalendarPermission() =>
      (super.noSuchMethod(Invocation.method(#requestCalendarPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestCameraPermission() =>
      (super.noSuchMethod(Invocation.method(#requestCameraPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestContactsPermission() =>
      (super.noSuchMethod(Invocation.method(#requestContactsPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestLocationPermission() =>
      (super.noSuchMethod(Invocation.method(#requestLocationPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestLocationAlwaysPermission() => (super
          .noSuchMethod(Invocation.method(#requestLocationAlwaysPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
      as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestLocationWhenInUsePermission() =>
      (super.noSuchMethod(
              Invocation.method(#requestLocationWhenInUsePermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestMediaLibraryPermission() =>
      (super.noSuchMethod(Invocation.method(#requestMediaLibraryPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestMicrophonePermission() =>
      (super.noSuchMethod(Invocation.method(#requestMicrophonePermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestPhonePermission() =>
      (super.noSuchMethod(Invocation.method(#requestPhonePermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestPhotosPermission() =>
      (super.noSuchMethod(Invocation.method(#requestPhotosPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestPhotosAddOnlyPermission() => (super
          .noSuchMethod(Invocation.method(#requestPhotosAddOnlyPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
      as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestRemindersPermission() =>
      (super.noSuchMethod(Invocation.method(#requestRemindersPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestSensorsPermission() =>
      (super.noSuchMethod(Invocation.method(#requestSensorsPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestSmsPermission() =>
      (super.noSuchMethod(Invocation.method(#requestSmsPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestSpeechPermission() =>
      (super.noSuchMethod(Invocation.method(#requestSpeechPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestStoragePermission() =>
      (super.noSuchMethod(Invocation.method(#requestStoragePermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus>
      requestIgnoreBatteryOptimizationsPermission() => (super.noSuchMethod(
          Invocation.method(#requestIgnoreBatteryOptimizationsPermission, []),
          returnValue: _i3.Future<_i4.PermissionStatus>.value(
              _i4.PermissionStatus.denied)) as _i3
          .Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestNotificationPermission() =>
      (super.noSuchMethod(Invocation.method(#requestNotificationPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestAccessMediaLocationPermission() =>
      (super.noSuchMethod(
              Invocation.method(#requestAccessMediaLocationPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestActivityRecognitionPermission() =>
      (super.noSuchMethod(
              Invocation.method(#requestActivityRecognitionPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestUnkwownPermission() =>
      (super.noSuchMethod(Invocation.method(#requestUnkwownPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestBluetoothPermission() =>
      (super.noSuchMethod(Invocation.method(#requestBluetoothPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestManageExternalStoragePermission() =>
      (super.noSuchMethod(
              Invocation.method(#requestManageExternalStoragePermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestSystemAlertWindowPermission() =>
      (super.noSuchMethod(
              Invocation.method(#requestSystemAlertWindowPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestInstallPackagesPermission() => (super
      .noSuchMethod(Invocation.method(#requestInstallPackagesPermission, []),
          returnValue: _i3.Future<_i4.PermissionStatus>.value(
              _i4.PermissionStatus.denied)) as _i3
      .Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestAppTrackingTransparencyPermission() =>
      (super.noSuchMethod(
              Invocation.method(#requestAppTrackingTransparencyPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestCriticalAlertsPermission() => (super
          .noSuchMethod(Invocation.method(#requestCriticalAlertsPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
      as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus>
      requestAccessNotificationPolicyPermission() => (super.noSuchMethod(
              Invocation.method(#requestAccessNotificationPolicyPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestBluetoothScanPermission() => (super
          .noSuchMethod(Invocation.method(#requestBluetoothScanPermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
      as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestBluetoothAdvertisePermission() =>
      (super.noSuchMethod(
              Invocation.method(#requestBluetoothAdvertisePermission, []),
              returnValue: _i3.Future<_i4.PermissionStatus>.value(
                  _i4.PermissionStatus.denied))
          as _i3.Future<_i4.PermissionStatus>);
  @override
  _i3.Future<_i4.PermissionStatus> requestBluetoothConnectPermission() => (super
      .noSuchMethod(Invocation.method(#requestBluetoothConnectPermission, []),
          returnValue: _i3.Future<_i4.PermissionStatus>.value(
              _i4.PermissionStatus.denied)) as _i3
      .Future<_i4.PermissionStatus>);
  @override
  _i3.Future<bool> openAppSettings() =>
      (super.noSuchMethod(Invocation.method(#openAppSettings, []),
          returnValue: _i3.Future<bool>.value(false)) as _i3.Future<bool>);
}
