// Mocks generated by Mockito 5.2.0 from annotations
// in auth_service/test/client.dart.
// Do not manually edit this file.

import 'dart:async' as _i8;

import 'package:auth_service/src/client.dart' as _i12;
import 'package:auth_service/src/method/apple.dart' as _i10;
import 'package:auth_service/src/method/facebook.dart' as _i9;
import 'package:auth_service/src/method/google.dart' as _i7;
import 'package:auth_service/src/method/twitter.dart' as _i11;
import 'package:firebase_auth/firebase_auth.dart' as _i5;
import 'package:flutter_facebook_auth/flutter_facebook_auth.dart' as _i2;
import 'package:google_sign_in/google_sign_in.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sign_in_with_apple/sign_in_with_apple.dart' as _i3;
import 'package:twitter_login/entity/auth_result.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDateTime_0 extends _i1.Fake implements DateTime {}

class _FakeLoginResult_1 extends _i1.Fake implements _i2.LoginResult {}

class _FakeAuthorizationCredentialAppleID_2 extends _i1.Fake
    implements _i3.AuthorizationCredentialAppleID {}

class _FakeAuthResult_3 extends _i1.Fake implements _i4.AuthResult {}

class _FakeUserCredential_4 extends _i1.Fake implements _i5.UserCredential {}

class _FakeGoogleSignInAuthentication_5 extends _i1.Fake
    implements _i6.GoogleSignInAuthentication {}

/// A class which mocks [GoogleAuthClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleAuthClient extends _i1.Mock implements _i7.GoogleAuthClient {
  MockGoogleAuthClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i6.GoogleSignInAccount?> signIn() =>
      (super.noSuchMethod(Invocation.method(#signIn, []),
              returnValue: Future<_i6.GoogleSignInAccount?>.value())
          as _i8.Future<_i6.GoogleSignInAccount?>);
}

/// A class which mocks [AccessToken].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccessToken extends _i1.Mock implements _i2.AccessToken {
  MockAccessToken() {
    _i1.throwOnMissingStub(this);
  }

  @override
  DateTime get expires => (super.noSuchMethod(Invocation.getter(#expires),
      returnValue: _FakeDateTime_0()) as DateTime);
  @override
  DateTime get lastRefresh =>
      (super.noSuchMethod(Invocation.getter(#lastRefresh),
          returnValue: _FakeDateTime_0()) as DateTime);
  @override
  String get userId =>
      (super.noSuchMethod(Invocation.getter(#userId), returnValue: '')
          as String);
  @override
  String get token =>
      (super.noSuchMethod(Invocation.getter(#token), returnValue: '')
          as String);
  @override
  String get applicationId =>
      (super.noSuchMethod(Invocation.getter(#applicationId), returnValue: '')
          as String);
  @override
  bool get isExpired =>
      (super.noSuchMethod(Invocation.getter(#isExpired), returnValue: false)
          as bool);
  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}

/// A class which mocks [FacebookAuthClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockFacebookAuthClient extends _i1.Mock
    implements _i9.FacebookAuthClient {
  MockFacebookAuthClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.LoginResult> login(
          {List<String>? permissions = const [r'email', r'public_profile'],
          _i2.LoginBehavior? loginBehavior = _i2.LoginBehavior.dialogOnly}) =>
      (super.noSuchMethod(
              Invocation.method(#login, [],
                  {#permissions: permissions, #loginBehavior: loginBehavior}),
              returnValue: Future<_i2.LoginResult>.value(_FakeLoginResult_1()))
          as _i8.Future<_i2.LoginResult>);
}

/// A class which mocks [AppleAuthClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppleAuthClient extends _i1.Mock implements _i10.AppleAuthClient {
  MockAppleAuthClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i3.AuthorizationCredentialAppleID> getAppleIDCredential(
          {String? rawNonce}) =>
      (super.noSuchMethod(
          Invocation.method(#getAppleIDCredential, [], {#rawNonce: rawNonce}),
          returnValue: Future<_i3.AuthorizationCredentialAppleID>.value(
              _FakeAuthorizationCredentialAppleID_2())) as _i8
          .Future<_i3.AuthorizationCredentialAppleID>);
}

/// A class which mocks [TwitterAuthClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTwitterAuthClient extends _i1.Mock implements _i11.TwitterAuthClient {
  MockTwitterAuthClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.AuthResult> login(
          {String? apiKey,
          String? apiSecretKey,
          String? redirectURI,
          bool? forceLogin = false}) =>
      (super.noSuchMethod(
              Invocation.method(#login, [], {
                #apiKey: apiKey,
                #apiSecretKey: apiSecretKey,
                #redirectURI: redirectURI,
                #forceLogin: forceLogin
              }),
              returnValue: Future<_i4.AuthResult>.value(_FakeAuthResult_3()))
          as _i8.Future<_i4.AuthResult>);
}

/// A class which mocks [AuthClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthClient extends _i1.Mock implements _i12.AuthClient {
  MockAuthClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i5.UserCredential> createUserWithEmailAndPassword(
          {String? email, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(#createUserWithEmailAndPassword, [],
                  {#email: email, #password: password}),
              returnValue:
                  Future<_i5.UserCredential>.value(_FakeUserCredential_4()))
          as _i8.Future<_i5.UserCredential>);
  @override
  _i8.Stream<_i5.User?> authStateChanges() =>
      (super.noSuchMethod(Invocation.method(#authStateChanges, []),
          returnValue: Stream<_i5.User?>.empty()) as _i8.Stream<_i5.User?>);
  @override
  _i8.Future<void> sendPasswordResetEmail(
          {String? email, _i5.ActionCodeSettings? actionCodeSettings}) =>
      (super.noSuchMethod(
          Invocation.method(#sendPasswordResetEmail, [],
              {#email: email, #actionCodeSettings: actionCodeSettings}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  _i8.Future<_i5.UserCredential> signInAnonymously() =>
      (super.noSuchMethod(Invocation.method(#signInAnonymously, []),
              returnValue:
                  Future<_i5.UserCredential>.value(_FakeUserCredential_4()))
          as _i8.Future<_i5.UserCredential>);
  @override
  _i8.Future<_i5.UserCredential> signInWithCredential(
          _i5.AuthCredential? credential) =>
      (super.noSuchMethod(
              Invocation.method(#signInWithCredential, [credential]),
              returnValue:
                  Future<_i5.UserCredential>.value(_FakeUserCredential_4()))
          as _i8.Future<_i5.UserCredential>);
  @override
  _i8.Future<_i5.UserCredential> signInWithEmailAndPassword(
          {String? email, String? password}) =>
      (super.noSuchMethod(
              Invocation.method(#signInWithEmailAndPassword, [],
                  {#email: email, #password: password}),
              returnValue:
                  Future<_i5.UserCredential>.value(_FakeUserCredential_4()))
          as _i8.Future<_i5.UserCredential>);
  @override
  _i8.Future<void> signOut() =>
      (super.noSuchMethod(Invocation.method(#signOut, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  _i8.Future<void> verifyPhoneNumber(
          {String? phoneNumber,
          _i5.PhoneVerificationCompleted? verificationCompleted,
          _i5.PhoneVerificationFailed? verificationFailed,
          _i5.PhoneCodeSent? codeSent,
          _i5.PhoneCodeAutoRetrievalTimeout? codeAutoRetrievalTimeout,
          Duration? timeout = const Duration(seconds: 30),
          int? forceResendingToken}) =>
      (super.noSuchMethod(
          Invocation.method(#verifyPhoneNumber, [], {
            #phoneNumber: phoneNumber,
            #verificationCompleted: verificationCompleted,
            #verificationFailed: verificationFailed,
            #codeSent: codeSent,
            #codeAutoRetrievalTimeout: codeAutoRetrievalTimeout,
            #timeout: timeout,
            #forceResendingToken: forceResendingToken
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
}

/// A class which mocks [AuthCredential].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthCredential extends _i1.Mock implements _i5.AuthCredential {
  MockAuthCredential() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get providerId =>
      (super.noSuchMethod(Invocation.getter(#providerId), returnValue: '')
          as String);
  @override
  String get signInMethod =>
      (super.noSuchMethod(Invocation.getter(#signInMethod), returnValue: '')
          as String);
  @override
  Map<String, dynamic> asMap() =>
      (super.noSuchMethod(Invocation.method(#asMap, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
}

/// A class which mocks [UserCredential].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserCredential extends _i1.Mock implements _i5.UserCredential {
  MockUserCredential() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [GoogleSignInAuthentication].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInAuthentication extends _i1.Mock
    implements _i6.GoogleSignInAuthentication {
  MockGoogleSignInAuthentication() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [GoogleSignInAccount].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockGoogleSignInAccount extends _i1.Mock
    implements _i6.GoogleSignInAccount {
  MockGoogleSignInAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get email =>
      (super.noSuchMethod(Invocation.getter(#email), returnValue: '')
          as String);
  @override
  String get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: '') as String);
  @override
  _i8.Future<_i6.GoogleSignInAuthentication> get authentication =>
      (super.noSuchMethod(Invocation.getter(#authentication),
              returnValue: Future<_i6.GoogleSignInAuthentication>.value(
                  _FakeGoogleSignInAuthentication_5()))
          as _i8.Future<_i6.GoogleSignInAuthentication>);
  @override
  _i8.Future<Map<String, String>> get authHeaders => (super.noSuchMethod(
          Invocation.getter(#authHeaders),
          returnValue: Future<Map<String, String>>.value(<String, String>{}))
      as _i8.Future<Map<String, String>>);
  @override
  _i8.Future<void> clearAuthCache() =>
      (super.noSuchMethod(Invocation.method(#clearAuthCache, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
}

/// A class which mocks [LoginResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginResult extends _i1.Mock implements _i2.LoginResult {
  MockLoginResult() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LoginStatus get status => (super.noSuchMethod(Invocation.getter(#status),
      returnValue: _i2.LoginStatus.success) as _i2.LoginStatus);
}

/// A class which mocks [AuthorizationCredentialAppleID].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockAuthorizationCredentialAppleID extends _i1.Mock
    implements _i3.AuthorizationCredentialAppleID {
  MockAuthorizationCredentialAppleID() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get authorizationCode => (super
          .noSuchMethod(Invocation.getter(#authorizationCode), returnValue: '')
      as String);
}

/// A class which mocks [AuthResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthResult extends _i1.Mock implements _i4.AuthResult {
  MockAuthResult() {
    _i1.throwOnMissingStub(this);
  }
}
