// Mocks generated by Mockito 5.2.0 from annotations
// in firebase_service/example/windows/flutter/ephemeral/.plugin_symlinks/firebase_service/example/linux/flutter/ephemeral/.plugin_symlinks/firebase_service/test/client.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:firebase_core/firebase_core.dart' as _i2;
import 'package:firebase_service/src/client.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeFirebaseApp_0 extends _i1.Fake implements _i2.FirebaseApp {}

/// A class which mocks [FirebaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseClient extends _i1.Mock implements _i3.FirebaseClient {
  MockFirebaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.FirebaseApp> get apps =>
      (super.noSuchMethod(Invocation.getter(#apps),
          returnValue: <_i2.FirebaseApp>[]) as List<_i2.FirebaseApp>);
  @override
  _i4.Future<_i2.FirebaseApp> initializeApp(
          {String? name, _i2.FirebaseOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #initializeApp, [], {#name: name, #options: options}),
              returnValue: Future<_i2.FirebaseApp>.value(_FakeFirebaseApp_0()))
          as _i4.Future<_i2.FirebaseApp>);
  @override
  _i2.FirebaseApp app(String? name) =>
      (super.noSuchMethod(Invocation.method(#app, [name]),
          returnValue: _FakeFirebaseApp_0()) as _i2.FirebaseApp);
}
