// Mocks generated by Mockito 5.3.0 from annotations
// in firebase_service/test/client.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_core/firebase_core.dart' as _i2;
import 'package:firebase_service/src/client.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseApp_0 extends _i1.SmartFake implements _i2.FirebaseApp {
  _FakeFirebaseApp_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseClient extends _i1.Mock implements _i3.FirebaseClient {
  MockFirebaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.FirebaseApp> get apps =>
      (super.noSuchMethod(Invocation.getter(#apps),
          returnValue: <_i2.FirebaseApp>[]) as List<_i2.FirebaseApp>);
  @override
  _i4.Future<_i2.FirebaseApp> initializeApp(
          {String? name, _i2.FirebaseOptions? options}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #initializeApp, [], {#name: name, #options: options}),
              returnValue: _i4.Future<_i2.FirebaseApp>.value(_FakeFirebaseApp_0(
                  this,
                  Invocation.method(#initializeApp, [], {#name: name, #options: options}))))
          as _i4.Future<_i2.FirebaseApp>);
  @override
  _i2.FirebaseApp app(String? name) =>
      (super.noSuchMethod(Invocation.method(#app, [name]),
              returnValue:
                  _FakeFirebaseApp_0(this, Invocation.method(#app, [name])))
          as _i2.FirebaseApp);
}
