// Mocks generated by Mockito 5.3.0 from annotations
// in permission_service/src/service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:permission_service/src/service.dart' as _i3;
import 'package:permission_service/src/types.dart' as _i2;
import 'package:riverpod/riverpod.dart' as _i4;
import 'package:state_notifier/state_notifier.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePermission_0 extends _i1.SmartFake implements _i2.Permission {
  _FakePermission_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeServiceStatus_1 extends _i1.SmartFake implements _i2.ServiceStatus {
  _FakeServiceStatus_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakePermissionStatus_2 extends _i1.SmartFake
    implements _i2.PermissionStatus {
  _FakePermissionStatus_2(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [PermissionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPermissionService extends _i1.Mock implements _i3.PermissionService {
  MockPermissionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i4.ErrorListener? _onError) =>
      super.noSuchMethod(Invocation.setter(#onError, _onError),
          returnValueForMissingStub: null);
  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
          as bool);
  @override
  _i5.Stream<_i2.Permission> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: _i5.Stream<_i2.Permission>.empty())
          as _i5.Stream<_i2.Permission>);
  @override
  _i2.Permission get state => (super.noSuchMethod(Invocation.getter(#state),
          returnValue: _FakePermission_0(this, Invocation.getter(#state)))
      as _i2.Permission);
  @override
  set state(_i2.Permission? value) =>
      super.noSuchMethod(Invocation.setter(#state, value),
          returnValueForMissingStub: null);
  @override
  _i2.Permission get debugState => (super.noSuchMethod(
          Invocation.getter(#debugState),
          returnValue: _FakePermission_0(this, Invocation.getter(#debugState)))
      as _i2.Permission);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i5.Future<void> initializeService() => (super.noSuchMethod(
      Invocation.method(#initializeService, []),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
  @override
  _i5.Future<_i2.ServiceStatus> getServiceStatus(_i2.ServiceType? type) =>
      (super.noSuchMethod(Invocation.method(#getServiceStatus, [type]),
          returnValue: _i5.Future<_i2.ServiceStatus>.value(_FakeServiceStatus_1(
              this, Invocation.method(#getServiceStatus, [type])))) as _i5
          .Future<_i2.ServiceStatus>);
  @override
  _i5.Future<_i2.PermissionStatus> requestPermissions(
          _i2.PermissionType? type) =>
      (super.noSuchMethod(Invocation.method(#requestPermissions, [type]),
              returnValue: _i5.Future<_i2.PermissionStatus>.value(
                  _FakePermissionStatus_2(
                      this, Invocation.method(#requestPermissions, [type]))))
          as _i5.Future<_i2.PermissionStatus>);
  @override
  _i5.Future<void> openAppSettings() => (super.noSuchMethod(
      Invocation.method(#openAppSettings, []),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
  @override
  bool updateShouldNotify(_i2.Permission? old, _i2.Permission? current) =>
      (super.noSuchMethod(
          Invocation.method(#updateShouldNotify, [old, current]),
          returnValue: false) as bool);
  @override
  _i4.RemoveListener addListener(_i6.Listener<_i2.Permission>? listener,
          {bool? fireImmediately = true}) =>
      (super.noSuchMethod(
          Invocation.method(
              #addListener, [listener], {#fireImmediately: fireImmediately}),
          returnValue: () {}) as _i4.RemoveListener);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
}
