targets:
  $default:
    builders:
      freezed:
        enabled: true
        generate_for:
          include:
            - lib/src/option.dart
      mockito:
        enabled: true
        generate_for:
          include:
            - test/client.dart
