targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - lib/**.dart
      - test/**.dart
      - integration_test/**.dart
    builders:
      freezed:
        enabled: true
      mockito:
        enabled: true
        generate_for:
          include:
            - test/client.dart
