name: logging_service
description: Module of Logging service.
version: 0.1.0
homepage: https://github.com/nagakuta
publish_to: https://dart.cloudsmith.io/nagakuta_flutter/logging_service/

environment:
  sdk: ">=2.17.1 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
