// Mocks generated by Mockito 5.3.0 from annotations
// in firebase_service/src/service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_core/firebase_core.dart' as _i3;
import 'package:firebase_core_platform_interface/firebase_core_platform_interface.dart'
    as _i2;
import 'package:firebase_service/src/service.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:riverpod/riverpod.dart' as _i6;
import 'package:state_notifier/state_notifier.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseOptions_0 extends _i1.SmartFake
    implements _i2.FirebaseOptions {
  _FakeFirebaseOptions_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseApp].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseApp extends _i1.Mock implements _i3.FirebaseApp {
  MockFirebaseApp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(Invocation.getter(#name), returnValue: '') as String);
  @override
  _i2.FirebaseOptions get options =>
      (super.noSuchMethod(Invocation.getter(#options),
              returnValue:
                  _FakeFirebaseOptions_0(this, Invocation.getter(#options)))
          as _i2.FirebaseOptions);
  @override
  bool get isAutomaticDataCollectionEnabled =>
      (super.noSuchMethod(Invocation.getter(#isAutomaticDataCollectionEnabled),
          returnValue: false) as bool);
  @override
  _i4.Future<void> delete() => (super.noSuchMethod(
      Invocation.method(#delete, []),
      returnValue: _i4.Future<void>.value(),
      returnValueForMissingStub: _i4.Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> setAutomaticDataCollectionEnabled(bool? enabled) =>
      (super.noSuchMethod(
              Invocation.method(#setAutomaticDataCollectionEnabled, [enabled]),
              returnValue: _i4.Future<void>.value(),
              returnValueForMissingStub: _i4.Future<void>.value())
          as _i4.Future<void>);
  @override
  _i4.Future<void> setAutomaticResourceManagementEnabled(bool? enabled) =>
      (super.noSuchMethod(
          Invocation.method(#setAutomaticResourceManagementEnabled, [enabled]),
          returnValue: _i4.Future<void>.value(),
          returnValueForMissingStub:
              _i4.Future<void>.value()) as _i4.Future<void>);
}

/// A class which mocks [FirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseService extends _i1.Mock implements _i5.FirebaseService {
  MockFirebaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onError(_i6.ErrorListener? _onError) =>
      super.noSuchMethod(Invocation.setter(#onError, _onError),
          returnValueForMissingStub: null);
  @override
  bool get mounted =>
      (super.noSuchMethod(Invocation.getter(#mounted), returnValue: false)
          as bool);
  @override
  _i4.Stream<Set<_i3.FirebaseApp>> get stream =>
      (super.noSuchMethod(Invocation.getter(#stream),
              returnValue: _i4.Stream<Set<_i3.FirebaseApp>>.empty())
          as _i4.Stream<Set<_i3.FirebaseApp>>);
  @override
  Set<_i3.FirebaseApp> get state =>
      (super.noSuchMethod(Invocation.getter(#state),
          returnValue: <_i3.FirebaseApp>{}) as Set<_i3.FirebaseApp>);
  @override
  set state(Set<_i3.FirebaseApp>? value) =>
      super.noSuchMethod(Invocation.setter(#state, value),
          returnValueForMissingStub: null);
  @override
  Set<_i3.FirebaseApp> get debugState =>
      (super.noSuchMethod(Invocation.getter(#debugState),
          returnValue: <_i3.FirebaseApp>{}) as Set<_i3.FirebaseApp>);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i4.Future<void> setUp(
          {String? apiKey,
          String? appId,
          String? messagingSenderId,
          String? projectId,
          String? authDomain,
          String? databaseURL,
          String? storageBucket,
          String? measurementId,
          String? trackingId,
          String? deepLinkURLScheme,
          String? androidClientId,
          String? iosClientId,
          String? iosBundleId,
          String? appGroupId}) =>
      (super.noSuchMethod(
              Invocation.method(#setUp, [], {
                #apiKey: apiKey,
                #appId: appId,
                #messagingSenderId: messagingSenderId,
                #projectId: projectId,
                #authDomain: authDomain,
                #databaseURL: databaseURL,
                #storageBucket: storageBucket,
                #measurementId: measurementId,
                #trackingId: trackingId,
                #deepLinkURLScheme: deepLinkURLScheme,
                #androidClientId: androidClientId,
                #iosClientId: iosClientId,
                #iosBundleId: iosBundleId,
                #appGroupId: appGroupId
              }),
              returnValue: _i4.Future<void>.value(),
              returnValueForMissingStub: _i4.Future<void>.value())
          as _i4.Future<void>);
  @override
  bool updateShouldNotify(
          Set<_i3.FirebaseApp>? old, Set<_i3.FirebaseApp>? current) =>
      (super.noSuchMethod(
          Invocation.method(#updateShouldNotify, [old, current]),
          returnValue: false) as bool);
  @override
  _i6.RemoveListener addListener(_i7.Listener<Set<_i3.FirebaseApp>>? listener,
          {bool? fireImmediately = true}) =>
      (super.noSuchMethod(
          Invocation.method(
              #addListener, [listener], {#fireImmediately: fireImmediately}),
          returnValue: () {}) as _i6.RemoveListener);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
}
