// Mocks generated by Mockito 5.3.0 from annotations
// in crashlytics_service/src/service.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:crashlytics_service/src/service.dart' as _i2;
import 'package:flutter/foundation.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CrashlyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrashlyticsService extends _i1.Mock
    implements _i2.CrashlyticsService {
  MockCrashlyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void recordException(Exception? exception, StackTrace? stack,
          {Iterable<_i3.DiagnosticsNode>? information = const []}) =>
      super.noSuchMethod(
          Invocation.method(#recordException, [exception, stack],
              {#information: information}),
          returnValueForMissingStub: null);
  @override
  void recordError(Object? error, StackTrace? stack,
          {Iterable<_i3.DiagnosticsNode>? information = const []}) =>
      super.noSuchMethod(
          Invocation.method(
              #recordError, [error, stack], {#information: information}),
          returnValueForMissingStub: null);
  @override
  void recordFlutterError(_i3.FlutterErrorDetails? flutterErrorDetails) =>
      super.noSuchMethod(
          Invocation.method(#recordFlutterError, [flutterErrorDetails]),
          returnValueForMissingStub: null);
  @override
  void setUserIdentifier(String? identifier) =>
      super.noSuchMethod(Invocation.method(#setUserIdentifier, [identifier]),
          returnValueForMissingStub: null);
}
